# ユーザーeikiのtoken
# y8IojJH8Fm3hVUauHbz4zaIPjfLXmyZPuH1HROPL


# ユーザ登録
###
POST http://localhost/api/register HTTP/1.1
content-type: application/json

{
    "name": "shima",
    "email" : "sample@gmail.com",
    "password": "pass"
}
###

# ログイン(認証情報をもとにaccess_tokenを取得)
###
POST https://intern-202108-e-shimamori.sandbox.yumemi.io/api/login HTTP/1.1
content-type: application/json

{
    "email" : "adm@co.jp",
    "password": "pass"
}
###

# ログアウト(認証情報を書き換える？)
###
http://localhost/api/user
Authorization: Bearer y8IojJH8Fm3hVUauHbz4zaIPjfLXmyZPuH1HROPL

###

# ユーザ情報取得
###
http://localhost/api/user
Authorization: Bearer 30|rL5nPgua9KduXqhRiHknhkakQI3Ht8GKg7NNgBeC

###

# チェックの可否はフロントエンドで制御
# チェックできない/チェックを外せない時はエラー

# ユーザが達成項目にチェックする
# "is_task_checked" : false は現在チェックしていないので「つけようとしている」
###
POST http://localhost/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer 3|xseypxVWRYw4rPup7jvRv5XgaSMFyhDwioFCe87n

{
    "task_id": 6,
    "is_task_checked" : false
}
###

# ユーザが達成項目のチェックを外す
# "is_task_checked" : true は現在チェックしているから「外そうとしている」
###
POST http://localhost/api/user HTTP/1.1
content-type: application/json
Authorization: Bearer 3|xseypxVWRYw4rPup7jvRv5XgaSMFyhDwioFCe87n

{
    "task_id": 6,
    "is_task_checked" : true
}
###

# 宝くじ情報取得
###
http://localhost/api/lottery
Authorization: Bearer 3|xseypxVWRYw4rPup7jvRv5XgaSMFyhDwioFCe87n

###


# 宝くじに応募する
###
POST http://localhost/api/lottery HTTP/1.1
content-type: application/json
Authorization: Bearer 3|xseypxVWRYw4rPup7jvRv5XgaSMFyhDwioFCe87n

{
    "voting_number": 100
}
###