
@token = Bearer 1|quxM2eD564IZy3lRfyp0bKickCiUCbWSXpCE2I5w
@aws = https://intern-202108-e-shimamori.sandbox.yumemi.io/api
@local = http://localhost/api
@path = {{local}}

# ログイン(認証情報をもとにaccess_tokenを取得)
###
POST {{path}}/login HTTP/1.1
content-type: application/json

{
    "email" : "gen@co.jp",
    "password": "word"
}
###

# ユーザ登録
###

POST {{path}}/register HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "eii",
    "email" : "eii@co.jp",
    "password": "word",
    "role_id": 2
}
###

# ユーザ情報取得
###
{{path}}/user
Authorization: {{token}}

###

# チェックの可否はフロントエンドで制御
# チェックできない/チェックを外せない時はエラー

# ユーザが達成項目にチェックする
# "is_task_checked" : false は現在チェックしていないので「つけようとしている」
###
POST {{path}}/user HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "task_id": 6,
    "is_task_checked" : false
}
###

# ユーザが達成項目のチェックを外す
# "is_task_checked" : true は現在チェックしているから「外そうとしている」
###
POST {{path}}/user HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "task_id": 6,
    "is_task_checked" : true
}
###

# 宝くじ情報取得
###
{{path}}/lottery
Authorization: {{token}}

###


# 宝くじに応募する
###
POST {{path}}/lottery HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "voting_number": 100
}
###

# タスクを追加する
###
POST {{path}}/task HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "name": "$request->name",
    "grade_id": 1,
    "genre_id": 1,
    "description": "$request->description",
    "is_positive_check": true
}
###

# タスクの更新
###
PUT {{path}}/task HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "id":6,
    "name": "update3",
    "grade_id": 2,
    "genre_id": 2,
    "description": "updated this description3"
}
###