# ログイン
# tokenベースのログインがlaravelに存在するのでそれを使いたい
# httpだけしかないのでssl化までするんだったらもう少し考える
# http/1.1でいいのかは後から考える
###
POST http://localhost/api/login HTTP/1.1
content-type: application/json

{
    "name": "YamadaTaro",
    "email": "sample@example.co.jp",
    "password": "password"
}
###

# ユーザ情報取得(アクセストークンが存在しないとき)
###
http://localhost/api/user
###

# ユーザ情報取得(headerに情報を入れるとき)
###
GET　http://localhost/api/user
Authorization: taro

###

# ユーザ情報取得(tokenが存在するとき)
###
http://localhost/api/user?access_token=shiro
###

# ユーザ情報取得(tokenが存在しないとき)
###
http://localhost/api/user?access_token=goro
###

# チェックの可否はフロントエンドで制御
# チェックできない/チェックを外せない時はエラー

# ユーザが達成項目にチェックする
# "is_task_checked" : false は現在チェックしていないので「つけようとしている」
###
POST http://localhost/api/user HTTP/1.1
content-type: application/json

{
    "task_id": 1,
    "is_task_checked" : false
}
###

# ユーザが達成項目のチェックを外す
# "is_task_checked" : true は現在チェックしているから「外そうとしている」
###
POST http://localhost/api/user HTTP/1.1
content-type: application/json

{
    "task_id": 1,
    "is_task_checked" : true
}
###

# 宝くじ情報取得
###
http://localhost/api/lottery
###


# 宝くじに応募する
###
POST http://localhost/api/lottery HTTP/1.1
content-type: application/json

{
    "user_id": 4,
    "voting_number": 100
}
###